# Generated by Django 5.1.1 on 2026-09-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(blank=True, upload_to="candidates/photos/"),
        ),
    ]
