"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse, unquote

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"

# Railway menyediakan nama host publik dan private sebagai variable otomatis.
# Keduanya harus diizinkan supaya health check dan trafik antar-service lolos.
_RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN")
_RAILWAY_HOSTS = [
    host for host in (_RAILWAY_PUBLIC_DOMAIN, os.getenv("RAILWAY_PRIVATE_DOMAIN")) if host
]

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "").split(",")
    if host.strip()
] + _RAILWAY_HOSTS

if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-7g)_lnbwl2e2xhw*(nr5h*+n1^by@gbgx0zc6qbaig46w1ojxp'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'users',
    'topics',
    'candidates',
    'votes',
    'comments',
    'dashboard',
    'roles',
    'election',
    'audit',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = "users.User"


# Daftar origin diizinkan dibaca dari CORS_ALLOWED_ORIGINS (dipisah koma).
# CORS_ALLOW_ALL_ORIGINS hanya untuk pengembangan; di produksi mencampur
# "allow all" dengan kredensial akan ditolak django-cors-headers.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "accept",
    "origin",
    "x-requested-with",
]

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ]
}



ASGI_APPLICATION = "core.asgi.application"

# Channel layer config pakai Redis. Railway meng-inject REDIS_URL; fallback
# localhost hanya berlaku di pengembangan.
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

# Plugin PostgreSQL Railway hanya meng-inject satu DATABASE_URL, bukan DB_NAME/
# DB_USER/DB_PASSWORD terpisah. railway.json sudah narrowing ke psycopg3.
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    _parsed = urlparse(_database_url)
    DATABASES["default"].update(
        {
            "NAME": unquote((_parsed.path or "").lstrip("/")),
            "USER": unquote(_parsed.username or ""),
            "PASSWORD": unquote(_parsed.password or ""),
            "HOST": _parsed.hostname or "",
            "PORT": str(_parsed.port or 5432),
        }
    )

if not DATABASES["default"]["NAME"]:
    raise RuntimeError(
        "Konfigurasi database kosong. Set DATABASE_URL (Railway) atau "
        "DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT."
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# 📲 WhatsApp Gateway Configuration
# Dukung Fonnte (https://fonnte.com) atau gateway lain
# Isi WA_GATEWAY_TOKEN di file .env dengan token API vendor WA Anda
# Jika kosong, sistem akan print log simulasi (mode development)
# =============================================================================
WA_GATEWAY_URL = os.getenv("WA_GATEWAY_URL", "https://api.fonnte.com/send")
WA_GATEWAY_TOKEN = os.getenv("WA_GATEWAY_TOKEN", None)

# =============================================================================
# 🔐 Vote Integrity / Encryption
# Wajib diganti nilai aman di produksi (64+ karakter acak) lewat .env.
# Dipakai AuthMiddleware untuk derive AES key & HMAC chain hash suara.
# =============================================================================
VOTE_ENCRYPTION_KEY = os.getenv("VOTE_ENCRYPTION_KEY", "")
RESULT_SIGNING_KEY = os.getenv("RESULT_SIGNING_KEY", "")
LEX_DSS_HMAC_SECRET = os.getenv("LEX_DSS_HMAC_SECRET", "")

# Kunci integritas suara diturunkan dari VOTE_ENCRYPTION_KEY. Menjalankan produksi
# dengan kunci dev berarti rantai hash suara bisa direproduksi siapa saja, jadi
# lebih baik gagal start daripada diam-diam memakai kunci lemah.
if not DEBUG:
    _MISSING = [
        name
        for name, value in (
            ("SECRET_KEY", SECRET_KEY),
            ("VOTE_ENCRYPTION_KEY", VOTE_ENCRYPTION_KEY),
        )
        if not value
    ]
    if _MISSING:
        raise RuntimeError(
            "Environment variable produksi wajib diisi: " + ", ".join(_MISSING)
        )
    if len(VOTE_ENCRYPTION_KEY) < 32:
        raise RuntimeError("VOTE_ENCRYPTION_KEY minimal 32 karakter di produksi.")

# Aktifkan broadcast real-time (WebSocket) saat suara baru masuk.
# Nilai selain "True" (mis. "0", "false") berarti nonaktif, bukan aktif.
VOTE_BROADCAST = os.getenv("VOTE_BROADCAST", "True").strip().lower() in {"true", "1", "yes", "on"}

# =============================================================================
# 📱 Sharing / Public (V7-A)
# BASE URL publik untuk membangun link share & QR yang bisa dibuka tanpa login.
# Di produksi ganti dengan domain publik (mis. https://evoting.example.id).
# =============================================================================
# PUBLIC_BASE_URL dipakai untuk menyusun link share/QR, jadi harus berupa URL
# lengkap ber-scheme. Railway hanya menyediakan hostname-nya, jadi disusun di sini.
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").rstrip("/")
if not PUBLIC_BASE_URL and _RAILWAY_PUBLIC_DOMAIN:
    PUBLIC_BASE_URL = f"https://{_RAILWAY_PUBLIC_DOMAIN}"
if not PUBLIC_BASE_URL:
    PUBLIC_BASE_URL = "http://localhost:8000"


# =============================================================================
# 🔔 Push Notifications (FCM)
# Kosongkan FCM_SERVER_KEY agar broadcast hanya tersimpan in-app (tanpa push).
# =============================================================================
FCM_SERVER_KEY = os.getenv("FCM_SERVER_KEY", "")

