# Generated by Django 5.1.1 on 2026-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='targets',
            field=models.IntegerField(default=0, help_text='Jumlah user yang menerima.'),
        ),
    ]
