# Generated by hand (V1: lapis integritas suara)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="previous_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="vote",
            name="integrity_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="vote",
            name="nonce",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="vote",
            name="encrypted_choice",
            field=models.TextField(blank=True, default=""),
        ),
    ]