# Generated by Django 5.1.1 on 2026-09-29 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0002_add_election_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="disclaimer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="topic_type",
            field=models.CharField(
                choices=[("election", "Election"), ("civic_poll", "Civic poll")],
                default="election",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CivicPollSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Document"),
                            ("transcript", "Transcript"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(max_length=255)),
                (
                    "segment_start_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "segment_end_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("transcript_excerpt", models.TextField(blank=True)),
                ("legal_audit", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="civic_source",
                        to="topics.topic",
                    ),
                ),
            ],
        ),
    ]
