# Generated by Django 5.1.1 on 2026-09-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0003_topic_disclaimer_topic_publication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="opens_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
