# Generated by Django 5.1.1 on 2026-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_closes_at_topic_opens_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='external_event_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
