# Generated by Django 5.1.1 on 2026-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_manage_elections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles (superadmin/netizen) tidak bisa dihapus.'),
        ),
    ]
