# Generated by Django 5.1.5 on 2025-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_netizen',
            field=models.BooleanField(default=False),
        ),
    ]
