"""Generated by hand for V2 (OTP verifikasi pemilih)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]